print("Pakistan Zindabad")
print("Hello World I am a student  of PIAIC from Faisalabad")
print("Pakistan Zindabad")
print("Pakistan Zindabad")
print("Pakistan Zindabad")
print("Pakistan Zindabad")
print("Pakistan Zindabad")
print("Pakistan Zindabad")
print("Pakistan Zindabad")
print("Pakistan Zindabad")
